-- SQL para la creación de la tabla SnibGeoportal
CREATE TABLE `SnibGeoportal` (
`grupobio` varchar(50) NOT NULL DEFAULT '',
`subgrupobio` varchar(250) NOT NULL DEFAULT '',
`familiavalida` varchar(50) NOT NULL DEFAULT '',
`generovalido` varchar(50) NOT NULL DEFAULT '',
`especievalida` varchar(100) NOT NULL DEFAULT '',
`nom059` varchar(512) NOT NULL DEFAULT '',
`cites` varchar(512) NOT NULL DEFAULT '',
`iucn` varchar(1024) NOT NULL DEFAULT '',
`prioritaria` varchar(100) NOT NULL DEFAULT '',
`exoticainvasora` varchar(50) NOT NULL DEFAULT '',
`longitud` double DEFAULT NULL,
`latitud` double DEFAULT NULL,
`estadomapa` varchar(50) NOT NULL DEFAULT '',
`municipiomapa` varchar(80) NOT NULL DEFAULT '',
`localidad` varchar(2048) NOT NULL DEFAULT '',
`fechacolecta` varchar(10) NOT NULL DEFAULT '',
`anp` varchar(250) NOT NULL DEFAULT '',
`categoriaresidenciaaves` varchar(100) NOT NULL DEFAULT '',
`formadecrecimiento` varchar(100) NOT NULL DEFAULT '',
`fuente` varchar(50) NOT NULL DEFAULT '',
`taxonextinto` enum('', 'SI', 'NO') NOT NULL DEFAULT '',
`usvserieVII` varchar(100) NOT NULL DEFAULT '',
`vegetacionserenanalcms` varchar(70) NOT NULL DEFAULT '',
`urlejemplar` varchar(255) NOT NULL DEFAULT '',
`idejemplar` varchar(32) NOT NULL DEFAULT '',
`ultimafechaactualizacion` date DEFAULT NULL,
`idnombrecatvalido` varchar(50) NOT NULL DEFAULT '',
`idnombrecat` varchar(50) NOT NULL DEFAULT '',
`reino` varchar(50) NOT NULL DEFAULT '',
`phylumdivision` varchar(50) NOT NULL DEFAULT '',
`clase` varchar(50) NOT NULL DEFAULT '',
`orden` varchar(50) NOT NULL DEFAULT '',
`familia` varchar(50) NOT NULL DEFAULT '',
`genero` varchar(50) NOT NULL DEFAULT '',
`especie` varchar(100) NOT NULL DEFAULT '',
`calificadordeterminacion` varchar(100) NOT NULL DEFAULT '',
`categoriainfraespecie` varchar(50) NOT NULL DEFAULT '',
`categoriainfraespecie2` varchar(50) NOT NULL DEFAULT '',
`autor` longtext NOT NULL,
`estatustax` varchar(20) NOT NULL DEFAULT '',
`reftax` varchar(255) NOT NULL DEFAULT '',
`taxonvalidado` varchar(2) NOT NULL DEFAULT '',
`reinovalido` varchar(50) NOT NULL DEFAULT '',
`phylumdivisionvalido` varchar(50) NOT NULL DEFAULT '',
`clasevalida` varchar(50) NOT NULL DEFAULT '',
`ordenvalido` varchar(50) NOT NULL DEFAULT '',
`categoriainfraespecievalida` varchar(50) NOT NULL DEFAULT '',
`categoriainfraespecie2valida` varchar(50) NOT NULL DEFAULT '',
`autorvalido` mediumtext NOT NULL,
`reftaxvalido` varchar(255) NOT NULL DEFAULT '',
`nombrecomun` text NOT NULL,
`ambiente` varchar(100) NOT NULL DEFAULT '',
`validacionambiente` varchar(100) NOT NULL DEFAULT '',
`endemismo` enum('','Cuasiendémica','Endémica','Semiendémica') NOT NULL DEFAULT '',
`nivelprioridad` enum('','Alta','Media','Menor') NOT NULL DEFAULT '',
`region` varchar(150) NOT NULL DEFAULT '',
`datum` varchar(50) NOT NULL DEFAULT '',
`geovalidacion` varchar(200) NOT NULL DEFAULT '',
`paismapa` varchar(50) NOT NULL DEFAULT '',
`claveestadomapa` varchar(10) NOT NULL DEFAULT '',
`mt24claveestadomapa` varchar(10) NOT NULL DEFAULT '',
`mt24nombreestadomapa` varchar(50) NOT NULL DEFAULT '',
`clavemunicipiomapa` varchar(10) NOT NULL DEFAULT '',
`mt24clavemunicipiomapa` varchar(10) NOT NULL DEFAULT '',
`mt24nombremunicipiomapa` varchar(80) NOT NULL DEFAULT '',
`incertidumbreXY` int(11) DEFAULT NULL,
`altitudmapa` smallint(6) DEFAULT NULL,
`usvserieI` varchar(100) NOT NULL DEFAULT '',
`usvserieII` varchar(100) NOT NULL DEFAULT '',
`usvserieIII` varchar(100) NOT NULL DEFAULT '',
`usvserieIV` varchar(100) NOT NULL DEFAULT '',
`usvserieV` varchar(100) NOT NULL DEFAULT '',
`usvserieVI` varchar(100) NOT NULL DEFAULT '',
`coleccion` varchar(150) NOT NULL DEFAULT '',
`institucion` varchar(255) NOT NULL DEFAULT '',
`paiscoleccion` varchar(50) NOT NULL DEFAULT '',
`numcatalogo` varchar(100) NOT NULL DEFAULT '',
`numcolecta` varchar(100) NOT NULL DEFAULT '',
`procedenciaejemplar`enum('','HumanObservation','PreservedSpecimen','FossilSpecimen','MaterialCitation','O
ccurrence','MaterialSample','MachineObservation','LivingSpecimen') NOT NULL DEFAULT '',
`determinador` varchar(512) NOT NULL DEFAULT '',
`fechadeterminacion` varchar(10) NOT NULL DEFAULT '',
`diadeterminacion` tinyint(4) DEFAULT NULL,
`mesdeterminacion` tinyint(4) DEFAULT NULL,
`aniodeterminacion` smallint(6) DEFAULT NULL,
`colector` varchar(512) NOT NULL DEFAULT '',
`diacolecta` tinyint(4) DEFAULT NULL,
`mescolecta` tinyint(4) DEFAULT NULL,
`aniocolecta` smallint(6) DEFAULT NULL,
`tipo` varchar(60) NOT NULL DEFAULT '',
`ejemplarfosil` enum('', 'SI', 'NO') NOT NULL DEFAULT '',
`proyecto` varchar(50) NOT NULL DEFAULT '',
`formadecitar` text NOT NULL,
`licenciauso` varchar(255) NOT NULL DEFAULT '',
`urlproyecto` varchar(255) NOT NULL DEFAULT '',
`urlorigen` varchar(255) NOT NULL DEFAULT '',
`obsusoinfo` varchar(512) NOT NULL DEFAULT '',
`version` varchar(7) NOT NULL DEFAULT '',
`idestadomapa` mediumint(8) DEFAULT NULL,
`idmunicipiomapa` int(10) DEFAULT NULL,
`mt24idestadomapa` mediumint(8) DEFAULT NULL,
`mt24idmunicipiomapa` int(10) DEFAULT NULL,
`idanpfederal1` mediumint(8) DEFAULT NULL,
`idanpfederal2` mediumint(8) DEFAULT NULL,
`especievalidabusqueda` varchar(100) NOT NULL,
`comentarioscat` varchar(1024) NOT NULL,
`comentarioscatvalido` varchar(1024) NOT NULL,
`homonimosgenero` varchar(512) NOT NULL,
`homonimosespecie` text NOT NULL,
`homonimosinfraespecie` varchar(255) NOT NULL,
`homonimosgenerocatvalido` varchar(255) NOT NULL,
`homonimosespeciecatvalido` text NOT NULL,
`homonimosinfraespeciecatvalido` varchar(255) NOT NULL,
`categoriataxonomica` varchar(50) NOT NULL
PRIMARY KEY (`idejemplar`),
KEY `grupobio` (`grupobio`),
KEY `anp` (`anp`),
KEY `latlon` (`longitud`,`latitud`),
KEY `paism` (`paismapa`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8

-- SQL para la creación de la tabla SnibMX
CREATE TABLE `SnibMX` (
  `idejemplar` varchar(32) NOT NULL DEFAULT '' COMMENT 'Clave generada por la CONABIO que identifica de manera única al ejemplar. Se asigna en el momento en que el ejemplar se integra al SNIB.',
  `numcatalogo` varchar(100) NOT NULL DEFAULT '' COMMENT 'Identificador único del ejemplar en la colección biológica, se le asigna cuando se incorpora a esta.',
  `numcolecta` varchar(100) NOT NULL DEFAULT '' COMMENT 'Identificador asignado por el recolector u observador para cada evento de recolecta u observación.',
  `coleccion` varchar(150) NOT NULL DEFAULT '' COMMENT 'Siglas y nombre de la colección que resguarda al ejemplar.',
  `institucion` varchar(255) NOT NULL DEFAULT '' COMMENT 'Siglas y nombre de la institución que custodia la colección científica, o que avala el registro de un ejemplar.',
  `fechacolecta` varchar(10) NOT NULL DEFAULT '' COMMENT 'Es la fecha del evento de recolecta u observación del ejemplar.',
  `aniocolecta` smallint(6) DEFAULT NULL COMMENT 'Año del evento de recolecta u observación del ejemplar.',
  `calificadordeterminacion` varchar(100) NOT NULL DEFAULT '' COMMENT 'Anotación acerca de la incertidumbre en la identificación taxonómica del ejemplar.',
  `procedenciaejemplar` enum('','HumanObservation','PreservedSpecimen','FossilSpecimen','MaterialCitation','Occurrence','MaterialSample','MachineObservation','LivingSpecimen') NOT NULL DEFAULT '' COMMENT 'Indica si el ejemplar proviene de un evento de recolecta, observación o de un reporte.',
  `ejemplarfosil` enum('','SI','NO') NOT NULL DEFAULT '' COMMENT 'Indica si el ejemplar es fósil.',
  `obsusoinfo` varchar(512) NOT NULL DEFAULT '' COMMENT 'Inconsistencias detectadas en los datos o información complementaria para el uso de los datos.',
  `formadecitar` text NOT NULL COMMENT 'Forma de citar los datos al hacer uso de estos o parte de los mismos.',
  `licenciauso` varchar(255) NOT NULL DEFAULT '' COMMENT 'Licencia de uso de la información del ejemplar.',
  `proyecto` varchar(50) NOT NULL DEFAULT '' COMMENT 'Referencia que identifica al proyecto.',
  `urlorigen` varchar(255) NOT NULL DEFAULT '' COMMENT 'Dirección de internet desde la cual originalmente se descargó la información del ejemplar en las páginas de GBIF o Naturalista.',
  `ultimafechaactualizacion` date DEFAULT NULL COMMENT 'Fecha de última actualización de los datos.',
  `version` varchar(7) NOT NULL DEFAULT '' COMMENT 'Versión que corresponde a las decisiones de los procesos de revisión aplicados a los datos en la CONABIO, así como, la información de referencia (mapas, catálogos, etc.) que se utiliza para realizar dicha revisión al integrar al SNIB. Cada vez que se cambien estás decisiones afectando la revisión de los datos, se cambiará la versión y se publicará el documento que describe los nuevos procesos y referencias correspondientes a la versión citada en este campo.',
  `familia` varchar(50) NOT NULL DEFAULT '' COMMENT 'Nombre científico de la familia en la que se ubica el ejemplar. La CONABIO realizó limpieza de la familia original en este campo, mediante la corrección de errores de escritura y la estandarización a sistemas de clasificación reconocidos por la comunidad científica.',
  `genero` varchar(50) NOT NULL DEFAULT '' COMMENT 'Nombre científico del género en el que se ubica el ejemplar. La CONABIO realizó limpieza de este campo mediante la corrección de errores de escritura y de datos que no corresponden con el campo así como la estandarización a sistemas de clasificación reconocidos por la comunidad científica.',
  `especie` varchar(100) NOT NULL DEFAULT '' COMMENT 'Nombre de la especie (binomio, trinomio, etc.) en la cual se determinó el ejemplar. La CONABIO realizó limpieza de este campo mediante la corrección de escritura y de datos que no corresponden con el campo.',
  `categoriainfraespecie` varchar(50) NOT NULL DEFAULT '' COMMENT 'Nombre de la categoría taxonómica correspondiente a alguna infraespecífica.',
  `categoriainfraespecie2` varchar(50) NOT NULL DEFAULT '' COMMENT 'Nombre de la categoría taxonómica correspondiente a alguna subinfraespecífica.',
  `reinovalido` varchar(50) NOT NULL DEFAULT '' COMMENT 'Nombre científico del Reino en el que se ubica el nombre válido del taxón correspondiente al ejemplar y que está reconocido en los catálogos de autoridades taxonómicas de la CONABIO o en otras referencias especializadas.',
  `phylumdivisionvalido` varchar(50) NOT NULL DEFAULT '' COMMENT 'Nombre científico de la división o el phylum en el que se ubica el nombre válido del taxón correspondiente al ejemplar y que está reconocido en los catálogos de autoridades taxonómicas de la CONABIO o en otras referencias especializadas.',
  `clasevalida` varchar(50) NOT NULL DEFAULT '' COMMENT 'Nombre científico de la clase en la que se ubica el nombre válido del taxón correspondiente al ejemplar y que está reconocido en los catálogos de autoridades taxonómicas de la CONABIO o en otras referencias especializadas.',
  `ordenvalido` varchar(50) NOT NULL DEFAULT '' COMMENT 'Nombre científico del orden en el que se ubica el nombre válido del taxón correspondiente al ejemplar y que está reconocido en los catálogos de autoridades taxonómicas de la CONABIO o en otras referencias especializadas.',
  `familiavalida` varchar(50) NOT NULL DEFAULT '' COMMENT 'Nombre científico de la familia en la que se ubica el nombre válido del taxón correspondiente al ejemplar y que está reconocido en los catálogos de autoridades taxonómicas de la CONABIO o en otras referencias especializadas.',
  `generovalido` varchar(50) NOT NULL DEFAULT '' COMMENT 'Nombre científico del género en el que se ubica el nombre válido del taxón correspondiente al ejemplar y que está reconocido en los catálogos de autoridades taxonómicas de la CONABIO o en otras referencias especializadas.',
  `especievalida` varchar(100) NOT NULL DEFAULT '' COMMENT 'Nombre válido de la especie (binomio, trinomio, etc.) reconocida en los catálogos de autoridades taxonómicas de la CONABIO o en otras referencias especializadas.',
  `categoriainfraespecievalida` varchar(50) NOT NULL DEFAULT '' COMMENT 'Nombre de la categoría taxonómica correspondiente a la infraespecífica del nombre válido.',
  `categoriainfraespecie2valida` varchar(50) NOT NULL DEFAULT '' COMMENT 'Nombre de la categoría taxonómica correspondiente a la subinfraespecífica del nombre válido.',
  `autorvalido` mediumtext NOT NULL COMMENT 'Nombre del autor o autores y año de la descripción del género, especie (binomio, trinomio, etc.) válida en catálogos de autoridades taxonómicas de la CONABIO o en otras referencias especializadas.',
  `grupobio` varchar(50) NOT NULL DEFAULT '' COMMENT 'Nombre utilizado para agrupar taxones con características biológicas generales similares asignado por la CONABIO.',
  `subgrupobio` varchar(250) NOT NULL DEFAULT '' COMMENT 'Nombre utilizado para agrupar taxones con características biológicas similares asignado por la CONABIO; pueden incluir nombres genéricos o el nombre común de la especie.',
  `cites` varchar(512) NOT NULL DEFAULT '' COMMENT 'Indica el grado de protección contra el comercio ilegal conforme a la Convención sobre el Comercio Internacional de Especies Amenazadas de Fauna y Flora Silvestres.',
  `iucn` varchar(1024) NOT NULL DEFAULT '' COMMENT 'Indica el estado de conservación de la especie conforme a la lista roja de la Unión Internacional para la Conservación de la Naturaleza (IUCN).',
  `nom059` varchar(512) NOT NULL DEFAULT '' COMMENT 'Indica la categoría de riesgo conforme a la NOM-059-SEMARNAT de la especie o la categoría infraespecífica.',
  `prioritaria` varchar(100) NOT NULL DEFAULT '' COMMENT 'Especies utilizadas para representar a otras especies o aspectos significativos del ambiente para conseguir un objetivo determinado de conservación.',
  `nivelprioridad` enum('','Alta','Media','Menor') NOT NULL DEFAULT '' COMMENT 'Nivel de prioridad asignado a la especie para su protección y conservación.',
  `exoticainvasora` varchar(50) NOT NULL DEFAULT '' COMMENT 'Indica si una especie está catalogada como exótica, exótica invasora o criptogénica para México.',
  `endemismo` enum('','Cuasiendémica','Endémica','Semiendémica') NOT NULL DEFAULT '' COMMENT 'Indica si el taxón tiene una distribución en México considerada como endémica, cuasiendémica o semiendémica, es decir, es originaria de un área geográfica limitada y solo está presente de manera natural en dicha área.',
  `longitud` double DEFAULT NULL COMMENT 'Longitud de la coordenada geográfica del sitio de recolecta u observación del ejemplar.',
  `latitud` double DEFAULT NULL COMMENT 'Latitud de la coordenada geográfica del sitio de recolecta u observación del ejemplar.',
  `paisoriginal` varchar(50) NOT NULL DEFAULT '' COMMENT 'Nombre del país en el que el ejemplar fue recolectado u observado.',
  `paismapa` varchar(50) NOT NULL DEFAULT '' COMMENT 'Nombre del país donde se ubica la coordenada geográfica registrada para el ejemplar, respecto a los mapas de división política de México incluyendo la zona económica exclusiva y los mapas de división política de otros países para la zona continental, utilizados para la validación geográfica realizada por la CONABIO.',
  `estadooriginal` varchar(55) NOT NULL DEFAULT '' COMMENT 'Nombre del estado o división política equivalente en la que el ejemplar fue recolectado u observado.',
  `estadomapa` varchar(50) NOT NULL DEFAULT '' COMMENT 'Nombre del estado o división política equivalente donde se ubica la coordenada geográfica registrada para el ejemplar, respecto al mapa de división política de México y de otros países utilizados para la validación geográfica realizada por la CONABIO.',
  `municipiooriginal` varchar(80) NOT NULL DEFAULT '' COMMENT 'Nombre del municipio en el que el ejemplar fue recolectado u observado.',
  `municipiomapa` varchar(80) NOT NULL DEFAULT '' COMMENT 'Nombre del municipio, en donde se ubica la coordenada geográfica registrada para el ejemplar, respecto al mapa de división política municipal de México utilizado para la validación geográfica realizada por la CONABIO.',
  `localidad` varchar(2048) NOT NULL DEFAULT '' COMMENT 'Referencia geográfica que describe la ubicación del lugar de recolecta u observación.',
  `anp` varchar(250) NOT NULL DEFAULT '' COMMENT 'Especifica la jurisdicción y nombre del área natural protegida (ANP) donde se ubica la coordenada geográfica registrada para el ejemplar respecto a mapas de México de ANP.',
  `altitudmapa` smallint(6) DEFAULT NULL COMMENT 'Altitud donde se ubica la coordenada geográfica obtenida del modelo de elevación ASTER GDEM2.',
  `regionmarinamapa` varchar(100) NOT NULL DEFAULT '' COMMENT 'Área geográfica donde se ubica la coordenada geográfica.',
  `incertidumbreXY` int(11) DEFAULT NULL COMMENT 'Valor de incertidumbre calculado para las coordenadas obtenidas usando el método punto-radio.',
  `cuencahidrograficamapa` varchar(100) NOT NULL DEFAULT '',
  `ecorregionterrestremapa` varchar(200) NOT NULL DEFAULT '',
  `geoportal` tinyint(1) DEFAULT NULL COMMENT 'Indica si la información del ejemplar esta publicada en el geoportal.'
) ENGINE=Aria DEFAULT CHARSET=utf8